//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_22._101_Khaustov_autorization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staffs
    {
        public int id_staff { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int id_role { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
